# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore YoussofPortfolio.API/YoussofPortfolio.API.csproj
    - name: Restore dependencies (YoussofPortfolio)
      run: dotnet restore YoussofPortfolio/YoussofPortfolio/YoussofPortfolio.csproj
    - name: Build
      run: dotnet build YoussofPortfolio.API/YoussofPortfolio.API.csproj --no-restore
    - name: Build (YoussofPortfolio)
      run: dotnet build YoussofPortfolio/YoussofPortfolio/YoussofPortfolio.csproj --no-restore
    - name: Test
      run: dotnet test YoussofPortfolio.API/YoussofPortfolio.API.csproj --no-build --verbosity normal
    - name: Test (YoussofPortfolio)
      run: dotnet test YoussofPortfolio/YoussofPortfolio/YoussofPortfolio.csproj --no-build --verbosity normal
